namespace: tks


tksinfo:
  nameOverride: "tks-info"
  fullnameOverride: "tks-info"
  replicaCount: 1
  image:
    repository: docker.io/sktcloud/tks-info
    pullPolicy: Always
    tag: "latest"
  imagePullSecrets: []

  service:
    type: LoadBalancer
    port: 9110

  serviceAccount:
    create: true
    annotations: {}
    name: "tks-info"

  args:
    tksContractAddress: tks-contract.tks.svc
    tksContractPort: 9110
    port: 9110
    dbUrl: postgresql.decapod-db.svc
    dbPort: 5432
    dbUser: tksuser
    dbPassword: tkspassword
  db:
    adminUser: postgres
    adminPassword: tacopassword
    dbName: tks

  ingress:
    enabled: false

  autoscaling:
    enabled: false

  podAnnotations: {}
  podSecurityContext: {}
  securityContext: {}
  tolerations: []
  affinity: {}
  resources: {}
