## global
namespace: tks
gitBaseUrl: https://github.com
gitAccount: decapod10
revision: main

db:
  adminUser: postgres
  adminPassword: secretPassword
  dbName: tks
  dbHost: postgresql.decapod-db.svc
  dbPort: 5432
  dbUser: tksuser
  dbPassword: secretPassword

## services
tksapi:
  nameOverride: "tks-api"
  fullnameOverride: "tks-api"
  replicaCount: 1
  image:
    repository: docker.io/sktcloud/tks-api
    pullPolicy: Always
    tag: 51034edc71aa6268fa5a575d1ad210caf2e5db85
  imagePullSecrets: []

  service:
    type: NodePort
    port: 9110

  serviceAccount:
    create: true
    annotations: {}
    name: "tks-api"

  tksAccount:
    accountId: admin
    organizationId: master
    password: admin

  args:
    port: 9110
    argoAddress: http://argo-workflows-operator-server.argo.svc
    argoPort: 2746

    externalGiteaUrl: http://localhost:30303

    imageRegistryUrl: harbor-dev.taco-cat.xyz/appserving
    harborPwSecret: harbor-core
    gitRepositoryUrl: github.com/openinfradev

    keycloakAddress: https://keycloak.taco-cat.xyz/auth
    keycloakAdmin: admin
    keycloakPassword: admin
    keycloakClientSecret: secret

    mailProvider: aws
    smtpHost: localhost
    smtpPort: 0
    smtpUsername: admin
    smtpPassword: admin
    smtpFromEmail: admin

    awsRegion: ap-northeast-2
    awsAccesssKeyId: AWS_SECRET_KEY
    awsSecretAccessKey: AWS_SECRET_ACCESS_KEY

  ingress:
    enabled: false

  autoscaling:
    enabled: false

tksbatch:
  nameOverride: "tks-batch"
  fullnameOverride: "tks-batch"
  replicaCount: 1
  image:
    repository: docker.io/sktcloud/tks-batch
    pullPolicy: Always
    tag: 4d11e054e03256bce3b505b911b3a4b00d4e1f88
  imagePullSecrets: []

  service:
    type: ClusterIP
    port: 9110

  serviceAccount:
    create: true
    annotations: {}
    name: "tks-batch"

  args:
    port: 9110
    argoAddress: http://argo-workflows-operator-server.argo.svc
    argoPort: 2746
    tksApiAddress: http://tks-api.tks.svc
    tksApiPort: 9110
    tksApiAccount: admin
    tksApiPassword: admin

  ingress:
    enabled: false

  autoscaling:
    enabled: false

tksconsole:
  nameOverride: "tks-console"
  fullnameOverride: "tks-console"
  replicaCount: 1
  image:
    repository: docker.io/sktcloud/tks-console
    pullPolicy: Always
    tag: 7f0cfd0acd1e451fb44c417246e62c3d53b0e8b8 
  imagePullSecrets: []

  service:
    type: ClusterIP
    port: 8080

  serviceAccount:
    create: true
    annotations: {}
    name: "tks-console"

  args:
    port: 80

  ingress:
    enabled: false

  autoscaling:
    enabled: false
