## global
namespace: tks
gitBaseUrl: https://github.com
gitAccount: decapod10
revision: main

db:
  adminUser: postgres
  adminPassword: tacopassword
  dbName: tks
  dbHost: postgresql.decapod-db.svc
  dbPort: 5432
  dbUser: tksuser
  dbPassword: tkspassword

## services
tksapi:
  nameOverride: "tks-api"
  fullnameOverride: "tks-api"
  replicaCount: 1
  image:
    repository: docker.io/sktcloud/tks-api
    pullPolicy: Always
    tag: 14354d15064195dc2e30feb46170c1e2ce1adb0f
  imagePullSecrets: []

  service:
    type: NodePort
    port: 9110

  serviceAccount:
    create: true
    annotations: {}
    name: "tks-api"

  args:
    port: 9110
    argoAddress: http://argo-workflows-operator-server.argo.svc
    argoPort: 2746
    imageRegistryUrl: "harbor-dev.taco-cat.xyz/appserving"
    harborPwSecret: "harbor-core"
    gitRepositoryUrl: "github.com/openinfradev"
    keycloakAddress: "http://tks-console.taco-cat.xyz"

  ingress:
    enabled: false

  autoscaling:
    enabled: false

tksbatch:
  nameOverride: "tks-batch"
  fullnameOverride: "tks-batch"
  replicaCount: 1
  image:
    repository: docker.io/sktcloud/tks-batch
    pullPolicy: Always
    tag: e34cff9726ad86301dcd2c87825ac2c19fb4b3ed
  imagePullSecrets: []

  service:
    type: ClusterIP
    port: 9110

  serviceAccount:
    create: true
    annotations: {}
    name: "tks-batch"

  args:
    port: 9110
    argoAddress: argo-workflows-operator-server.argo.svc
    argoPort: 2746

  ingress:
    enabled: false

  autoscaling:
    enabled: false
