{{- if .Values.cluster.eksEnabled }}
apiVersion: {{ .Values.api.group.controlplane }}/v1beta2
kind: AWSManagedControlPlane
metadata:
  name: {{ .Values.cluster.name }}
  namespace: {{ .Release.Namespace }}
spec:
  eksClusterName: {{ .Values.cluster.name }}
  region: {{ .Values.cluster.region }}
  sshKeyName: {{ .Values.sshKeyName }}
  version: {{ .Values.cluster.kubernetesVersion }}
  addons:
    {{- toYaml .Values.cluster.eksAddons | nindent 4 }}
{{- end }}
