{{- $azPostfixList := list "a" "b" "c" "d" "e" "f" }}
{{- $envAll := . }}
{{- range .Values.machinePool }}
{{- if eq $envAll.Values.api.version "v1alpha3" }}
apiVersion: exp.{{ $envAll.Values.api.group.cluster }}/{{ $envAll.Values.api.version }}
{{- else }}
apiVersion: {{ $envAll.Values.api.group.cluster }}/{{ $envAll.Values.api.version }}
{{- end }}
kind: MachinePool
metadata:
  name: {{ $envAll.Values.cluster.name }}-mp-{{ .name }}
  namespace: {{ $envAll.Release.Namespace }}
spec:
  clusterName: {{ $envAll.Values.cluster.name }}
  replicas: {{ .replicas }}
  template:
    metadata:
      {{- with .labels }}
      labels: 
        {{- toYaml . | nindent 12 }}
      {{- end }}
    spec:
      bootstrap:
        configRef:
          apiVersion: {{ $envAll.Values.api.group.bootstrap }}/{{ $envAll.Values.api.version }}
          kind: KubeadmConfig
          name: {{ $envAll.Values.cluster.name }}-mp-{{ .name }}
          namespace: {{ $envAll.Release.Namespace }}
      clusterName: {{ $envAll.Values.cluster.name }}
      infrastructureRef:
        apiVersion: {{ $envAll.Values.api.group.infrastructure }}/{{ $envAll.Values.api.version }}
        kind: AWSMachinePool
        name: {{ $envAll.Values.cluster.name }}-mp-{{ .name }}
        namespace: {{ $envAll.Release.Namespace }}
      version: {{ $envAll.Values.cluster.kubernetesVersion }}
---
apiVersion: {{ $envAll.Values.api.group.infrastructure }}/{{ $envAll.Values.api.version }}
kind: AWSMachinePool
metadata:
  name: {{ $envAll.Values.cluster.name }}-mp-{{ .name }}
  namespace: {{ $envAll.Release.Namespace }}
spec:
  awsLaunchTemplate:
    instanceType: {{ .machineType }}
    sshKeyName: {{ $envAll.Values.sshKeyName }}
    iamInstanceProfile: "nodes.cluster-api-provider-aws.sigs.k8s.io"
    rootVolume:
      size: {{ .rootVolume.size }}
      type: {{ .rootVolume.type }}
    {{- if .ami }}
    ami:
      {{- toYaml . | nindent 8 }}
    {{- end }}
  maxSize: {{ .maxSize }}
  minSize: {{ .minSize }}
  subnets:
  - filters:
    - name: "tag:sigs.k8s.io/cluster-api-provider-aws/role"
      values:
      - "private"
    - name: "tag:Name"
      values:
      - "*{{ $envAll.Values.cluster.name }}*"
---
apiVersion: {{ $envAll.Values.api.group.bootstrap }}/{{ $envAll.Values.api.version }}
kind: KubeadmConfig
metadata:
  name: {{ $envAll.Values.cluster.name }}-mp-{{ .name }}
  namespace: {{ $envAll.Release.Namespace }}
spec:
  joinConfiguration:
    nodeRegistration:
      kubeletExtraArgs:
        cloud-provider: aws
      name: '{{`{{ ds.meta_data.local_hostname }}`}}'
{{- end }}
