{{- if .Values.deployMgmtRbacOnly.enabled }}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-autoscaler-management
  namespace: {{ .Values.deployMgmtRbacOnly.targetNamespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cluster-autoscaler-management
subjects:
- kind: ServiceAccount
  name: cluster-autoscaler
  namespace: {{ .Values.deployMgmtRbacOnly.targetNamespace }}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-autoscaler-management
  namespace: {{ .Values.deployMgmtRbacOnly.targetNamespace }}
rules:
  - apiGroups:
    - cluster.x-k8s.io
    resources:
    - machinedeployments
    - machinedeployments/scale
    - machines
    - machinesets
    - machinepools
    - machinepools/scale
    - awsmanagedmachinepools
    verbs:
    - get
    - list
    - update
    - watch
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cluster-autoscaler
  namespace: {{ .Values.deployMgmtRbacOnly.targetNamespace }}
{{- end }}
