policies:
  protectPerNamespace:
    enabled: true
    constraints:
    - name: protectbytks
      parameters:
        namespaces: 
        - "taco-system"
        - "kube-system"
        - "lma"
        - "tks-msa"
        allowedUsers: 
        - "kubernetes-admin"
        - "system:serviceaccount:kube-system:argocd-manager"
        allowedGroup: "system:masters"