{{- if and .Values.fluentbit.enabled }}
{{- range $i, $input := .Values.fluentbit.targetLogs }}
---
apiVersion: fluentbit.fluent.io/v1alpha2
kind: ClusterInput
metadata:
  name: input-{{ trimSuffix ".*"  $input.tag }}
  namespace: {{ $.Release.Namespace }}
  labels:
    fluentbit.fluent.io/enabled: "true"
    app.kubernetes.io/version: v0.0.1
spec:
  tail: 
    db: /fluent-bit/tail
{{- if and $input.bufferChunkSize }}
    bufferChunkSize: {{ $input.bufferChunkSize }}
{{- else}}
    bufferChunkSize: 1M
{{- end}}
{{- if and $input.bufferMaxSize }}
    bufferMaxSize: {{ $input.bufferMaxSize }}
{{- else}}
    bufferMaxSize: 1M
{{- end}}
{{- if and $input.memBufLimit }}
    memBufLimit: {{ $input.memBufLimit }}
{{- else}}
    memBufLimit: 5M
{{- end}}
    parser: {{ $input.parser }}
    path: {{ $input.path }}
    tag: "{{ $input.tag }}"
{{- with $input.extraArgs }}
{{ toYaml . | indent 4 }}
{{- end }}
{{- end }}
{{- end }}
