{{- if and .Values.fluentbit.enabled .Values.fluentbit.alerts.enabled -}}
---
kind: PrometheusRule
apiVersion: monitoring.coreos.com/v1
metadata:
  annotations:
    prometheus-operator-validated: 'true'
  name: {{ template "fluentbit-operator.fullname" . }}-alert
  namespace:  {{ .Values.fluentbit.alerts.namespace }}
spec:
  groups:
    - name: log-based-alert
      rules:
        - alert: log-page
          annotations:
            message: >- 
              {{ .Values.fluentbit.alerts.message }}
            summary: >-
              {{ .Values.fluentbit.alerts.summary }}
          expr: taco_logging_system_alert{severity="critical"} == 1
          labels:
            severity: page
        - alert: log-critical
          annotations:
            message: >- 
              {{ .Values.fluentbit.alerts.message }}
            summary: >-
              {{ .Values.fluentbit.alerts.summary }}
          expr: taco_logging_system_alert{severity="critical"} == 1
          labels:
            severity: critical
        - alert: log-info
          annotations:
            message: >- 
              {{ .Values.fluentbit.alerts.message }}
            summary: >-
              {{ .Values.fluentbit.alerts.summary }}
          expr: taco_logging_system_alert{severity="info"} == 1
          labels:
            severity: info
        - alert: log-warning
          annotations:
            message: >- 
              {{ .Values.fluentbit.alerts.message }}
            summary: >-
              {{ .Values.fluentbit.alerts.summary }}
          expr: taco_logging_system_alert{severity="warning"} == 1
          labels:
            severity: warning
{{- end}}