apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
  name: tks-admin-console
rules:
- apiGroups:
    - ""
  resources:
    - nodes
    - secrets
  verbs:
    - get
    - watch
    - list
