{{- if .Values.tksadminconsole.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "tks-admin-console.serviceAccountName" . }}
  labels:
    {{- include "tks-admin-console.labels" . | nindent 4 }}
  {{- with .Values.tksadminconsole.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
