apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tks-api
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - secrets
  - services
  - pods
  - namespaces
  - events
  verbs:
  - get
  - watch
  - list
