{{- if .Values.tksapi.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "tks-api.serviceAccountName" . }}
  labels:
    {{- include "tks-api.labels" . | nindent 4 }}
  {{- with .Values.tksapi.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
secrets:
- name: tks-api-token
{{- end }}
