apiVersion: v1
data:
  ACCOUNT_ID: {{ .Values.tksapi.tksAccount.accountId | b64enc }}
  ORGANIZATION_ID: {{ .Values.tksapi.tksAccount.organizationId | b64enc }}
  PASSWORD: {{ .Values.tksapi.tksAccount.password | b64enc }}
kind: Secret
metadata:
  name: tks-api-secret
  namespace: argo
type: Opaque
