{{- if .Values.vpc.enabled }}
{{- $envAll := . }}
{{- range .Values.subnets }}
{{ if eq .isPrivate false }}
---
apiVersion: ec2.services.k8s.aws/v1alpha1
kind: ElasticIPAddress
metadata:
  name: {{ $envAll.Values.name }}-nat-{{ .az }}
spec:
  tags:
    - key: name
      value: {{ $envAll.Values.name }}
{{- end }}
{{- end }}
{{- end }}
