{{- if .Values.vpc.enabled }}
---
apiVersion: ec2.services.k8s.aws/v1alpha1
kind: InternetGateway
metadata:
  name: {{ .Values.name }}
spec:
  vpcRef:
    from:
      name: {{ .Values.name }}
  tags:
    - key: name
      value: {{ .Values.name }}
{{- end }}
