{{- if .Values.instances.enabled }}
{{- $envAll := . }}
{{- with .Values.instances.bastion }}
---
apiVersion: ec2.services.k8s.aws/v1alpha1
kind: Instance
metadata:
  name: {{ $envAll.Values.name }}-bastion
spec:
  imageID: {{ $envAll.Values.imageID }}
  instanceType: {{ .instanceType }}
  subnetID: {{ .subnetID }}
  {{- with .securityGroupIDs }}
  securityGroupIDs:
    {{- toYaml . | nindent 2 }}
  {{- end }}
  monitoring: 
    enabled: false
  blockDeviceMappings:
  - deviceName: /dev/sda1
    ebs: 
      deleteOnTermination: true
      encrypted: false
      volumeSize: {{ .volumeSize }}
      volumeType: gp2
  keyName: {{ $envAll.Values.instances.keyName }}
  tags:
    - key: name
      value: {{ $envAll.Values.name }}
{{- end }}
{{- end }}
