{{- if .Values.vpc.enabled }}
{{- $envAll := . }}
{{- range .Values.subnets }}
---
apiVersion: ec2.services.k8s.aws/v1alpha1
kind: RouteTable
metadata:
  name: {{ $envAll.Values.name }}-{{ if eq .isPrivate true }}private{{ else }}public{{ end }}-{{ .az }}
spec:
  routes:
    - destinationCIDRBlock: 0.0.0.0/0
      {{- if eq .isPrivate true }}
      natGatewayRef:
        from:
          name: {{ $envAll.Values.name }}-{{ .az }}
      {{- else }}
      gatewayRef:
        from:
          name: {{ $envAll.Values.name }}
      {{- end }}
  vpcRef:
    from:
      name: {{ $envAll.Values.name }}
  tags:
    - key: name
      value: {{ $envAll.Values.name }}
{{- end }}
{{- end }}
