apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.postgres.secretName }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  postgres-password:  {{ .Values.postgres.password | b64enc | quote }}
  postgres-username:  {{ .Values.postgres.username | b64enc | quote }}
