namespace: istio-system
strategy: production
sampling:
  param: 100
ingress:
  enabled: false
collector:
  maxReplicas: 5
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 1
      memory: 2Gi
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: servicemesh
            operator: In
            values:
            - enabled
storage:
  esIndexCleaner:
    enabled: true
    numberOfDays: 7
    schedule: "55 04 * * *"
  options:
    es:
      indexPrefix: jaeger
      username: elastic
      password: tacoword
      tlsCa: /etc/ssl/certs/tls.crt
      serverUrls: https://eck-elasticsearch-es-http.istio-system.svc:9200
      secretName: eck-elasticsearch-es-http-certs-public
query:
  basePath: /
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: servicemesh
            operator: In
            values:
            - enabled

elasticsearch:
  image:
    repository: docker.io/openstackhelm/heat
    tag: newton
    pullPolicy: IfNotPresent
  host: eck-elasticsearch-es-http.istio-system.svc.cluster.local
  port: 9200
  elasticPasswordSecret: eck-elasticsearch-es-elastic-user
  user:
    enabled: true
    username: taco-jaeger
    password: tacoword