{{- if .Values.cassandra.user.enabled }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: create-cassandra-user
  namespace: {{ .Values.namespace }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "20"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    metadata:
      name: create-cassandra-user-template
    spec:
      {{- with .Values.cassandra.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: cassandra-user
        image: "{{ .Values.cassandra.image }}"
        imagePullPolicy: "{{ .Values.cassandra.imagePullPolicy }}"
        env:
        - name: CASS_USERNAME
          valueFrom:
            secretKeyRef:
              name: {{ .Values.cassandra.passwordSecret  }}
              key: username
        - name: CASS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.cassandra.passwordSecret  }}
              key: password
        command:
        - timeout
        - 5m
        - /tmp/create_user.sh
        volumeMounts:
        - name: create-cassandra-user-cm
          mountPath: /tmp/create_user.sh
          subPath: create_user.sh
          readOnly: true
      volumes:
      - name: create-cassandra-user-cm
        configMap:
          name: create-cassandra-user-cm
          defaultMode: 0777
      restartPolicy: OnFailure
{{- end}}