{{- if .Values.policies.protectPerNamespace.enabled }}
{{- $envAll := . }}
{{- range .Values.policies.protectPerNamespace.constraints }}
---
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: ProtectPerNamespace
metadata:
  name: {{.name | lower }}
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "1"  
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: 
        - Pods
        - Configmaps
        - Secrets
        - Deployments
        - Statefulsets
        - Daemonsets
        - Services
        - Ingresses
    namespaces:
      {{- toYaml .parameters.namespaces | nindent 6 }}
  parameters:
    allowedUsers: 
      {{- toYaml .parameters.allowedUsers | nindent 6 }}
    allowedGroup: {{ .parameters.allowedGroup }}
{{- end}}
{{- end}}