{{- if .Values.objectStorage.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.objectStorage.secretName }}
  namespace: {{ .Release.Namespace }}
stringData:
  objstore.yml: |-
    type: {{ default "s3" .Values.objectStorage.type}}
    config:  {{ toYaml .Values.objectStorage.rawConfig | nindent 6}}
{{- end }}