# Default values for fluentbit-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

## Provide a name in place of fluentbit-operator for `app:` labels
##
nameOverride: ""

## Provide a k8s version to auto dashboard import script example: kubeTargetVersionOverride: 1.16.6
##
kubeTargetVersionOverride: ""

## Provide a name to substitute for the full names of resources
##
fullnameOverride: ""

## Labels to apply to all resources
##
commonLabels: {}
# scmhash: abc123
# myLabel: aakkmd

image:
  init:
    repository: docker
    tag: 19.03
    pullPolicy: IfNotPresent
  hyperkube:
    repository: k8s.gcr.io/hyperkube
    tag: v1.17.6
    pullPolicy: IfNotPresent
  fluentbit:
    repository: ghcr.io/openinfradev/fluentbit
    tag: 25bc31cd4333f7f77435561ec70bc68e0c73a194
  exporter:
    repository: siim/logalert-exporter
    tag: v0.1.1
    pullPolicy: IfNotPresent
  elasticsearchTemplates: 
    repository: docker.io/openstackhelm/heat
    tag: newton
    pullPolicy: IfNotPresent
##
global:
  rbac:
    create: true
    pspEnabled: false
    pspAnnotations: {}
      ## Specify pod annotations
      ## Ref: https://kubernetes.io/docs/concepts/policy/pod-security-policy/#apparmor
      ## Ref: https://kubernetes.io/docs/concepts/policy/pod-security-policy/#seccomp
      ## Ref: https://kubernetes.io/docs/concepts/policy/pod-security-policy/#sysctl
      ##
      # seccomp.security.alpha.kubernetes.io/allowedProfileNames: '*'
      # seccomp.security.alpha.kubernetes.io/defaultProfileName: 'docker/default'
      # apparmor.security.beta.kubernetes.io/defaultProfileName: 'runtime/default'

  ## Reference to one or more secrets to be used when pulling images
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
  ##
  imagePullSecrets: []
  # - name: "image-pull-secret"

  base_cluster_url: cluster.local

## Deploy a Fluentbit instance
##
fluentbit:

  enabled: false

  ## Annotations for Fluentbit
  ##
  annotations: {}

  ## Service account for Fluentbites to use.
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/
  ##
  serviceAccount:
    create: true
    name: fluentbit

  daemonset:
    spec:
      ## Tolerations for use with node taints
      ## ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
      ##
      tolerations: 
      - key: node-role.kubernetes.io/master
        operator: Exists
      - key: node-role.kubernetes.io/node
        operator: Exists

      ## Define which Nodes the Pods are scheduled on.
      ## ref: https://kubernetes.io/docs/user-guide/node-selection/
      ##
      # nodeSelector: 
      #   taco-lma: enabled

      ## Secrets is a list of Secrets in the same namespace as the Fluentbit object, which shall be mounted into the Fluentbit Pods.
      ## The Secrets are mounted into /etc/fluentbit/secrets/. Secrets changes after initial creation of a Fluentbit object are not
      ## reflected in the running Pods. To change the secrets mounted into the Fluentbit Pods, the object must be deleted and recreated
      ## with the new list of secrets.
      ##
      secrets: []

      ## ConfigMaps is a list of ConfigMaps in the same namespace as the Fluentbit object, which shall be mounted into the Fluentbit Pods.
      ## The ConfigMaps are mounted into /etc/fluentbit/configmaps/.
      ##
      configMaps: []

      ## Standard object’s metadata. More info: https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#metadata
      ## Metadata Labels and Annotations gets propagated to the fluentbit pods.
      ##
      podMetadata: {}
      # labels:
      #   app: fluentbit
      #   k8s-app: fluentbit

      ## Pod anti-affinity can prevent the scheduler from placing Fluentbit replicas on the same node.
      ## The default value "soft" means that the scheduler should *prefer* to not schedule two replica pods onto the same node but no guarantee is provided.
      ## The value "hard" means that the scheduler is *required* to not schedule two replica pods onto the same node.
      ## The value "" will disable pod anti-affinity so that no anti-affinity rules will be configured.
      podAntiAffinity: ""

      ## If anti-affinity is enabled sets the topologyKey to use for anti-affinity.
      ## This can be changed to, for example, failure-domain.beta.kubernetes.io/zone
      ##
      podAntiAffinityTopologyKey: kubernetes.io/hostname

      ## Assign custom affinity rules to the fluentbit instance
      ## ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/
      ##
      affinity: {}
      # nodeAffinity:
      #   requiredDuringSchedulingIgnoredDuringExecution:
      #     nodeSelectorTerms:
      #     - matchExpressions:
      #       - key: kubernetes.io/e2e-az-name
      #         operator: In
      #         values:
      #         - e2e-az1
      #         - e2e-az2

      ## Resource limits & requests
      ##
      resources: {}
      # requests:
      #   memory: 400Mi

      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 2000

      ## 	Priority class assigned to the Pods
      ##
      priorityClassName: ""

      ## Default rulset to send exporter
      ## format is "level: keyword"   for example "critical: error"
      ## VERY VERY VERY IMPORTANT ==> At least one tuple should be defined
    
  targetLogs:
  - name: dockerlog
    tag: kube.*
    path: /var/log/containers/*.log
    type: fluent
    index: container
    parser: docker
    memBufLimit: 20MB
    bufferChunkSize: 2M
    bufferMaxSize: 5M
    do_not_store_as_default: false
    multi_index:
    - key: "$kubernetes['namespace_name']"
      value: "kube-system|lma|fed|argo|openstack"
      index: platform
    extraArgs: {}
  - name: syslog
    tag: kubenode.*
    path: /var/log/syslog
    type: syslog
    index: syslog
    parser: syslog-rfc5424
    extraArgs: {}
  - name: etcd
    tag: etcdnode.*
    path: /var/log/etcd.log
    type: etcd
    index: etcd
    parser: docker
    extraArgs: {}
  outputs:
    es:
      enabled: false
      createuser: false
      username: fluentbit
      password: password
      elasticPasswordSecret: elasticsearch-es-elastic-user
      host: taco-elasticsearch-es-http.lma.svc.cluster.local
      port: 9200
      template:
        enabled: false
        url: https://taco-elasticsearch-es-http.lma.svc.cluster.local:9200
        ilms:
        - name: hot-delete-14days
          json:
            policy:
              phases:
                hot:
                  actions:
                    rollover:
                      max_size: 30gb
                      max_age: 1d
                      max_docs: 5000000000
                    set_priority:
                      priority: 100
                delete:
                  min_age: 14d
                  actions:
                    delete: {}
        - name: hot-delete-7days
          json:
            policy:
              phases:
                hot:
                  actions:
                    rollover:
                      max_size: 30gb
                      max_age: 1d
                      max_docs: 5000000000
                    set_priority:
                      priority: 100
                delete:
                  min_age: 7d
                  actions:
                    delete: {}
        - name: hot-delete-3hour
          json:
            policy:
              phases:
                hot:
                  actions:
                    rollover:
                      max_size: 30gb
                      max_age: 1h
                      max_docs: 5000000000
                    set_priority:
                      priority: 100
                delete:
                  min_age: 3h
                  actions:
                    delete: {}
        templates:
        - name: platform
          json:
            index_patterns: "platform*"
            settings:
              refresh_interval: 30s
              number_of_shards: 3
              number_of_replicas: 1
              index.lifecycle.name: hot-delete-14days
              index.lifecycle.rollover_alias: platform
        - name: application
          json:
            index_patterns: "container*"
            settings:
              refresh_interval: 30s
              number_of_shards: 3
              number_of_replicas: 1
              index.lifecycle.name: hot-delete-3hour
              index.lifecycle.rollover_alias: container
        - name: syslog
          json:
            index_patterns: "syslog*"
            settings:
              refresh_interval: 30s
              number_of_shards: 2
              number_of_replicas: 1
              index.lifecycle.name: hot-delete-14days
              index.lifecycle.rollover_alias: syslog

    kafka:
      enabled: false
      broker: my-kafka-0.my-kafka-headless.lma.svc.cluster.local:9092,
      topics: taco
    http:
      enabled: false

  alerts:
    enabled: false
    namespace: fed
    message: |-
      {{ $labels.container }} in {{ $labels.pod }} ({{ $labels.taco_cluster }}/{{ $labels.namespace }} ) generate a error due to log = {{ $labels.log }}
    summary: |-
      {{ $labels.container }} in {{ $labels.pod }} ({{ $labels.taco_cluster }}/{{ $labels.namespace }} ) generate a error
    # ******************** VERY IMPORTANT ************
    # current version of log-exporter(siim/logalert-exporter:v0.1.1) support only one notification
    # so you should not define more than one rule at installation
    # To define multiple phrase, make custom resouce for filter by hands
    rules:
    - name: example
      severity: critical
      regex: "update.?error"

  # Define cluster name which is shown in collected logs
  clusterName: unknown
  exclude:
  - key: "$kubernetes['container_name']"
    value: kibana
logExporter:
  enabled: false
  serviceMonitor:
    enabled: false
    interval: 1m
# nodeSelector: 
#   taco-lma: enabled
