apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tks-app-serve-lcm.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "tks-app-serve-lcm.labels" . | nindent 4 }}
spec:
  {{- if not .Values.tksappservelcm.autoscaling.enabled }}
  replicas: {{ .Values.tksappservelcm.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "tks-app-serve-lcm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.tksappservelcm.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "tks-app-serve-lcm.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.tksappservelcm.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "tks-app-serve-lcm.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.tksappservelcm.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.tksappservelcm.securityContext | nindent 12 }}
          image: "{{ .Values.tksappservelcm.image.repository }}:{{ .Values.tksappservelcm.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.tksappservelcm.image.pullPolicy }}
          ports:
            - name: tksappservelcm
              containerPort: {{ .Values.tksappservelcm.args.port }}
              protocol: TCP
          command:
            - /app/server
          args: [
            "-port", "{{ .Values.tksappservelcm.args.port }}",
            "-info-address", "{{ .Values.tksappservelcm.args.tksInfoAddress }}",
            "-info-port", "{{ .Values.tksappservelcm.args.tksInfoPort }}",
            "-argo-address", "{{ .Values.tksappservelcm.args.argoAddress }}",
            "-argo-port", "{{ .Values.tksappservelcm.args.argoPort }}",
            "-image-registry-url", "{{ .Values.tksappservelcm.args.imageRegistryUrl }}",
            "-harbor-pw-secret", "{{ .Values.tksappservelcm.args.harborPwSecret }}",
          ]
          resources:
            {{- toYaml .Values.tksappservelcm.resources | nindent 12 }}
      {{- with .Values.tksappservelcm.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tksappservelcm.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tksappservelcm.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
