apiVersion: v1
kind: Service
metadata:
  name: {{ include "tks-app-serve-lcm.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "tks-app-serve-lcm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.tksappservelcm.service.type }}
  ports:
    - port: {{ .Values.tksappservelcm.service.port }}
      targetPort: {{ .Values.tksappservelcm.args.port }}
      protocol: TCP
  selector:
    {{- include "tks-app-serve-lcm.selectorLabels" . | nindent 4 }}
