apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tks-contract.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "tks-contract.labels" . | nindent 4 }}
spec:
  {{- if not .Values.tkscontract.autoscaling.enabled }}
  replicas: {{ .Values.tkscontract.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "tks-contract.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.tkscontract.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "tks-contract.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.tkscontract.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "tks-contract.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.tkscontract.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.tkscontract.securityContext | nindent 12 }}
          image: "{{ .Values.tkscontract.image.repository }}:{{ .Values.tkscontract.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.tkscontract.image.pullPolicy }}
          ports:
            - name: tks-contract
              containerPort: {{ .Values.tkscontract.args.port }}
              protocol: TCP
          command:
            - /app/server
          args: [
            "-port", "{{ .Values.tkscontract.args.port }}",
            "-info-address", "{{ .Values.tkscontract.args.tksInfoAddress }}",
            "-info-port", "{{ .Values.tkscontract.args.tksInfoPort }}",
            "-argo-address", "{{ .Values.tkscontract.args.argoAddress }}",
            "-argo-port", "{{ .Values.tkscontract.args.argoPort }}",
            "-revision", "{{ .Values.tkscontract.args.revision }}",
            "-dbhost", "{{ .Values.db.dbUrl }}",
            "-dbport", "{{ .Values.db.dbPort }}",
            "-dbuser", "{{ .Values.db.dbUser }}",
            "-dbpassword", "{{ .Values.db.dbPassword }}",
          ]
          resources:
            {{- toYaml .Values.tkscontract.resources | nindent 12 }}
      {{- with .Values.tkscontract.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tkscontract.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tkscontract.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
