{{- if .Values.tkscontract.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "tks-contract.serviceAccountName" . }}
  labels:
    {{- include "tks-contract.labels" . | nindent 4 }}
  {{- with .Values.tkscontract.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
