apiVersion: v1
kind: Service
metadata:
  name: {{ include "tks-info.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "tks-info.labels" . | nindent 4 }}
spec:
  type: {{ .Values.tksinfo.service.type }}
  ports:
    - port: {{ .Values.tksinfo.service.port }}
      targetPort: {{ .Values.tksinfo.args.port }}
      protocol: TCP
  selector:
    {{- include "tks-info.selectorLabels" . | nindent 4 }}
