apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tks-cluster-lcm.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "tks-cluster-lcm.labels" . | nindent 4 }}
spec:
  {{- if not .Values.tksclusterlcm.autoscaling.enabled }}
  replicas: {{ .Values.tksclusterlcm.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "tks-cluster-lcm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.tksclusterlcm.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "tks-cluster-lcm.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.tksclusterlcm.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "tks-cluster-lcm.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.tksclusterlcm.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.tksclusterlcm.securityContext | nindent 12 }}
          image: "{{ .Values.tksclusterlcm.image.repository }}:{{ .Values.tksclusterlcm.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.tksclusterlcm.image.pullPolicy }}
          ports:
            - name: tks-cluster-lcm
              containerPort: {{ .Values.tksclusterlcm.args.port }}
              protocol: TCP
          command:
            - /app/server
          args: [
            "-port", "{{ .Values.tksclusterlcm.args.port }}",
            "-info-address", "{{ .Values.tksclusterlcm.args.infoAddress }}",
            "-info-port", "{{ .Values.tksclusterlcm.args.infoPort }}",
            "-contract-address", "{{ .Values.tksclusterlcm.args.contractAddress }}",
            "-contract-port", "{{ .Values.tksclusterlcm.args.contractPort }}",
            "-argo-address", "{{ .Values.tksclusterlcm.args.argoAddress }}",
            "-argo-port", "{{ .Values.tksclusterlcm.args.argoPort }}",
            "-revision", "{{ .Values.revision }}",
            "-git-base-url", "{{ .Values.gitBaseUrl }}",
            "-git-account", "{{ .Values.gitAccount }}",
          ]
          resources:
            {{- toYaml .Values.tksclusterlcm.resources | nindent 12 }}
      {{- with .Values.tksclusterlcm.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tksclusterlcm.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tksclusterlcm.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
