{{- if .Values.tksbatch.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "tks-batch.serviceAccountName" . }}
  labels:
    {{- include "tks-batch.labels" . | nindent 4 }}
  {{- with .Values.tksbatch.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
secrets:
- name: tks-batch-token
{{- end }}
