apiVersion: keycloak.org/v1alpha1
kind: Keycloak
metadata:
  name: {{ .Values.keycloak.name }}
  labels:
    app: {{ .Values.keycloak.name }}
spec:
  instances: {{ .Values.keycloak.replicas }}
  externalDatabase:
    enabled: {{ .Values.keycloak.externalDatabase.enabled }}
  {{- if not .Values.keycloak.externalDatabase.enabled }}
  storageClassName: {{ .Values.keycloak.storageClassName }}
  {{- end }}
  externalAccess:
    enabled: {{ .Values.keycloak.externalAccessEnabled }}
    host: {{ .Values.keycloak.externalAccessHost }}
