{{- range .Values.keycloakRealm }}
apiVersion: keycloak.org/v1alpha1
kind: KeycloakRealm
metadata:
  name: {{ .name }}
  labels:
    realm: {{ .name }}
spec:
  realm:
    realm: "{{ .name }}"
    enabled: True
    displayName: "{{ .displayName }}"
  instanceSelector:
    matchLabels:
      app: "{{ .keycloakSelector }}"
{{- end }}
